-- AlterTable
ALTER TABLE `Game` MODIFY `currentTurn` ENUM('PLAYER', 'DEALER') NOT NULL DEFAULT 'PLAYER',
    MODIFY `winner` ENUM('PLAYER_WIN', 'DEALER_WIN', 'PENDING') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `Participant` ADD COLUMN     `money` INTEGER NOT NULL DEFAULT 0;